### ISSUE TITLE
Fix the deployment issue

### ISSUE THREAD

**Issue by mohamedsgap** [techfellows/website#9]
Right now, we deploy the page on `GitHub Pages` and we you visit the website it only render the `HTML` no style!, we need to fix this issue, I think the problem this a conflict between deploying the website as project under `website` name or deploying it as `home` app! 

**Hint** 
Read this https://v2.docusaurus.io/docs/deployment#deploying-to-github-pages

**Comment by ruslanguns** [comment]
This issue is because the base URL is not reading the correct path, since that Github Pages has a website as a directory and breaks the path for source imports (right now the correct one is (/website/xxx). I believe it can be fixed by editing  the line 
https://github.com/techfellows/website/blob/f1a31600d234f65aba0635bcc509575c3ad65c7f/docusaurus.config.js#L5

By setting it to: baseUrl: "/website/", otherwise if it does not work, adding manually the base tag in the head of your html would fix it. [more info](https://www.w3schools.com/tags/tag_base.asp)

Would you like me to PR this solution?

**Comment by ruslanguns** [comment]
I've send already the fix on #10 , tried it locally and worked as expected with no need of modifying the built files (that would be tricky) if it fails please don't hesitate to tell me

**Comment by mohamedsgap** [comment]
Thanks @ruslanguns 💯 👍
